// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // Provide both shapes to be compatible with different Prisma CLI expectations
  datasource: {
    url: process.env.DATABASE_URL!,
  },
  datasources: {
    db: {
      url: process.env.DATABASE_URL!,
    },
  },
});


